### ISSUE TITLE
WHAT on slacking object throws exception

### ISSUE THREAD

**Issue by bbkr** [lizmat/Object-Delayed#1]
```perl6
use Object::Delayed;
my $x = slack { ... };
say $x.WHAT;
```

```
Cannot resolve caller handler(Object::Trampoline: ); none of these signatures match:
    (Object::Trampoline:U: \object, |args is raw)
    (Object::Trampoline:D \SELF: |args is raw)
  in block <unit> at -e line 1
```

**Comment by lizmat** [comment]
Thanks for the report: this is actually an issue of `Object::Trampoline`, but one I'm afraid will not be easy to fix.  This is because `.WHAT` codegens to an `nqp::what`, and that apparently cannot handle the magic that is inside of the `Object::Trampoline` class.

I will try to look at this in more depth soonish, but am afraid it won't be easy and/or would require changes to nqp (and thus only be fixed with future versions of Rakudo).
