### ISSUE TITLE
Run slack when handled rw method is assigned to?

### ISSUE THREAD

**Issue by Altreus** [lizmat/Object-Delayed#5]
If the delayed object handles stuff, the stuff isn't fully available until you do something with it first. Specifically, a `rw` accessor is not writable until the object is created - but the reader part works fine.

```
> class A { has $.a is rw; has $.b }
(A)
> class B { has $.delegate handles <a b> = slack { A.new(a => 1, b => 2); } }
(B)
> my $b = B.new; say $b.delegate.defined; # avoid REPL autovivifying delegate
False
> $b.a = 3;
Cannot modify an immutable Int (1)
  in block <unit> at <unknown file> line 1
> $b.a
1
> my $c = B.new;
B.new(delegate => A.new(a => 1, b => 2))
> say $c.delegate.defined
True
> $c.a = 3;
3
```

**Comment by lizmat** [comment]
I've just uploaded a newer version of `Object::Delayed` to CPAN.  Should become available with `zef` shortly.  The problem is really caused by `Lock.protect` de-containerizing, but that decontainerization was specifically added to prevent some segfaults 2 years ago.  So I added some code to `Object::Trampoline` (the actual workhorse) to make sure a container is not removed.  This appears to fix your example code.

Thanks for trying `Object::Delayed` and taking it to new places!
